/**
 * Server rendering.
 *
 * aiweave.org is generated by renderToStaticMarkup with no hydration, and any
 * consumer on Next.js, Remix or Astro renders these components on a server
 * too. A component that reads `window`, `document` or `matchMedia` during
 * render — rather than inside an effect — throws there, and the failure is a
 * broken build rather than a broken pixel.
 *
 * The globals are genuinely removed for the duration, not merely undefined:
 * a component that guards with `typeof window === "undefined"` passes, one
 * that guards with `window?.matchMedia` does not, and only the first is
 * actually safe on Node.
 */
import { afterEach, describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { SPECIMENS } from "./fixtures";

const BROWSER_GLOBALS = ["window", "document", "navigator", "localStorage", "requestAnimationFrame"] as const;

function withoutBrowserGlobals<T>(fn: () => T): T {
  const saved = new Map<string, PropertyDescriptor | undefined>();
  for (const key of BROWSER_GLOBALS) {
    saved.set(key, Object.getOwnPropertyDescriptor(globalThis, key));
    Object.defineProperty(globalThis, key, { value: undefined, configurable: true, writable: true });
  }
  try {
    return fn();
  } finally {
    for (const [key, descriptor] of saved) {
      if (descriptor) Object.defineProperty(globalThis, key, descriptor);
      else delete (globalThis as Record<string, unknown>)[key];
    }
  }
}

afterEach(() => {
  // Guard against a thrown assertion leaving the environment stripped.
  expect(typeof globalThis.document).not.toBe("undefined");
});

describe("static rendering", () => {
  for (const specimen of SPECIMENS) {
    it(`${specimen.name} renders on a server with no DOM`, () => {
      const html = withoutBrowserGlobals(() => renderToStaticMarkup(specimen.element));
      expect(typeof html).toBe("string");
    });
  }

  it("produces real markup, not an empty string", () => {
    for (const specimen of SPECIMENS) {
      const html = withoutBrowserGlobals(() => renderToStaticMarkup(specimen.element));
      expect(html.length, `${specimen.name} rendered nothing on the server`).toBeGreaterThan(0);
    }
  });

  it("emits no raw undefined or NaN into the markup", () => {
    for (const specimen of SPECIMENS) {
      const html = withoutBrowserGlobals(() => renderToStaticMarkup(specimen.element));
      expect(html, `${specimen.name} leaked an undefined value`).not.toContain('="undefined"');
      expect(html, `${specimen.name} leaked NaN`).not.toContain("NaN");
    }
  });
});
